version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@2.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "onaoshi"
          tag: "${CIRCLE_SHA1}"
      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
      #     family: "onaoshi-service63333"
      #     cluster: "duyen-cluster"
      #     container-image-name-updates: "container=onaoshi-service63333,tag=latest"