version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "onaoshi"
          context: dev
          tag: '11'
