version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: '234514745840.dkr.ecr.ap-northeast-1.amazonaws.com'
          aws-access-key-id: "AKIATNGRLBHYDPPYHGIZ"
          aws-secret-access-key: "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"
          context: "myContext"
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: 'myProfileName'
          repo: "onaoshi"
          skip-when-tags-exist: false
          tag: 'latest'
