version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "onaoshi"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"